
declare module 'lucide-react' {
  import { FC, SVGProps } from 'react';
  export interface IconProps extends SVGProps<SVGSVGElement> {
    size?: number | string;
    color?: string;
    strokeWidth?: number | string;
  }
  export type Icon = FC<IconProps>;
  
  export const Plus: Icon;
  export const X: Icon;
  export const Search: Icon;
  export const ShoppingBag: Icon;
  export const ChefHat: Icon;
  export const Sparkles: Icon;
  export const Clock: Icon;
  export const ShoppingCart: Icon;
  export const CircleCheck: Icon;
  export const CircleAlert: Icon;
  export const MapPin: Icon;
  export const Navigation: Icon;
  export const ExternalLink: Icon;
  export const RefreshCw: Icon;
  export const Eye: Icon;
  export const Check: Icon;
  export const Filter: Icon;
  export const Camera: Icon;
  export const LoaderCircle: Icon;
  export const Store: Icon;
  export const Database: Icon;
  export const Calendar: Icon;
  export const Settings: Icon;
  export const Play: Icon;
  export const SquareCheck: Icon;
  export const ArrowRight: Icon;
  export const ArrowLeft: Icon;
  export const PlayCircle: Icon;
  export const Flame: Icon;
  export const Activity: Icon;
  export const Lightbulb: Icon;
  export const Sun: Icon;
  export const Moon: Icon;
  export const Heart: Icon;
  export const CalendarDays: Icon;
  export const Trash2: Icon;
  export const FileSpreadsheet: Icon;
  export const BarChart3: Icon;
  export const TrendingUp: Icon;
  export const PieChart: Icon;
  export const Crown: Icon;
  export const Zap: Icon;
  export const Star: Icon;
  export const Share2: Icon;
  export const LocateFixed: Icon;
  export const Edit2: Icon;
  export const ScanBarcode: Icon;
  export const Wine: Icon;
  export const Volume2: Icon;
  export const ScanEye: Icon;
  export const Languages: Icon;
  export const Layers: Icon;
  export const Mic: Icon;
  export const MicOff: Icon;
  export const Dices: Icon;
  export const Scale: Icon;
  export const HelpCircle: Icon;
  export const Thermometer: Icon;
  export const Users: Icon;
  export const Utensils: Icon;
  export const Timer: Icon;
  export const Pause: Icon;
  export const RotateCcw: Icon;
  export const CircleX: Icon;
}